<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../SV_PotC/PartOfTheCommunity.csproj" />
    <Reference Include="StardewModdingAPI">
      <HintPath>/home/brandon/.steam/debian-installation/steamapps/common/Stardew Valley/StardewModdingAPI.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
