name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Make Stardew Valley Files
      run: |
        mkdir ~/stardew
        touch ~/stardew/Stardew\ Valley.dll
            
    - name: Verify game files
      run: ls -R ~/stardew

    - name: Write StardewValley.targets
      run: |
        echo '<Project>' > ~/stardewvalley.targets
        echo '  <PropertyGroup>' >> ~/stardewvalley.targets
        echo '    <GamePath>/home/runner/stardew</GamePath>' >> ~/stardewvalley.targets
        echo '  </PropertyGroup>' >> ~/stardewvalley.targets
        echo '</Project>' >> ~/stardewvalley.targets

    - name: Verify StardewValley.targets
      run: cat ~/stardewvalley.targets

    - name: Download SMAPI
      run: |
        curl -L -o smapi.zip https://github.com/Pathoschild/SMAPI/releases/download/4.2.1/SMAPI-4.2.1-installer.zip
        unzip -q smapi.zip -d smapi

    - name: verify SMAPI files
      run: |
        ls -R smapi

    - name: Install SMAPI
      run: |
       ./smapi/SMAPI\ 4.2.1\ installer/internal/linux/SMAPI.Installer --no-prompt --install --game-path ~/stardew
       

    # 🔽 Setup .NET and Build/Test project
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
