name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # 🔽 Install SteamCMD and Stardew Valley
    - name: Install dependencies for SteamCMD
      run: |
        sudo apt update
        sudo apt install -y lib32gcc-s1

    - name: Install SteamCMD
      run: |
        mkdir -p ~/steamcmd
        cd ~/steamcmd
        curl -s https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz | tar -xz

    - name: Install Stardew Valley via SteamCMD
      env:
        STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
        STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
      run: |
        cd ~/steamcmd
        ./steamcmd.sh \
          +login "$STEAM_USERNAME" "$STEAM_PASSWORD" \
          +force_install_dir "$HOME/stardew" \
          +app_update 413150 validate \
          +quit

    - name: Verify game files
      run: ls -R ~/stardew
    
    - name: Write StardewValley.targets
      run: |
        echo '<Project>' > ~/stardewvalley.targets
        echo '  <PropertyGroup>' >> ~/stardewvalley.targets
        echo '    <GamePath>$$([System.Environment]::GetEnvironmentVariable("HOME"))/stardew</GamePath>' >> ~/stardewvalley.targets
        echo '  </PropertyGroup>' >> ~/stardewvalley.targets
        echo '</Project>' >> ~/stardewvalley.targets

    # 🔽 Setup .NET and Build/Test project
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
